# frontend/Dockerfile
FROM node:20-alpine

WORKDIR /app

# Exponemos el puerto por defecto de Vite
EXPOSE 5173

# Comando temporal para mantener el contenedor vivo sin código
CMD ["tail", "-f", "/dev/null"]