events { 
        worker_connections 1024; 
    }

http {
    upstream recepcion_backend {
        least_conn; # Requisito de la rúbrica
        # Docker DNS resolverá "recepcion" a las 3 IPs de las réplicas
        server recepcion:8000; 
    }

    server {
        listen 80;

        location / {
            proxy_pass http://recepcion_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}