stream {
    upstream gateway_instances {
        server 127.0.0.1:3001;
        server 127.0.0.1:3002;
        server 127.0.0.1:3003;
    }

    # Si necesitas que Nginx reciba el tráfico TCP de los sensores y lo mande al clúster
    server {
        listen 1883; # Puerto MQTT estándar
        proxy_pass gateway_instances;
    }
}